### ISSUE TITLE
Meaningless Data on ADSBDATA Table and GUI

### ISSUE THREAD

**Issue by cmbahadir** [cmbahadir/PlaneSpotter#1]
**Test Environment:** Apache2 - Raspberry Pi - MySQL DB
**Version:** v0.0

**Test Steps:**
1- Run httppost_adsb.py
2- mysql - select * from ADSBDATA.
3- Navigate to http://192.168.1.12

Test Data: modes1.bin

**Expected Result:**

![image](https://user-images.githubusercontent.com/8937774/38171567-bcfa5570-35a4-11e8-87dd-180c51d14e21.png)

**Actual Result:**

On GUI:

![image](https://user-images.githubusercontent.com/8937774/38171525-0764eb80-35a4-11e8-82c6-0c4fc999a755.png)

On MySQL:

![image](https://user-images.githubusercontent.com/8937774/38171560-8318d69c-35a4-11e8-8409-469e4653f1ae.png)

**Comment by hsynercn** [comment]
Ya nasil oluyormus bakalim

**Comment by cmbahadir** [comment]
Selam Huseyin,

Decode icin https://github.com/antirez/dump1090'i kullaniyorum, problem burdan gelen basliklari filtrelemeden db'ye insert etmem. Aklimda 3 secenek var.

1- dump1090'daki asagidaki printfleri silmek. (Onceden boyle yapmistim.)

https://github.com/antirez/dump1090/blob/d4be3b8a25765de9f36f2aff697f61f914c65f13/dump1090.c#L1810

2- add.php'de insert ederken baslik satirini filtrelemek.

https://github.com/cmbahadir/PlaneSpotter/blob/master/add.php

3- HTTP Post sirasinda filtrelemek.

https://github.com/cmbahadir/PlaneSpotter/blob/master/raspberrypi/httppost_adsb.py

**Not: Bu arada su anda development environment ayakta degil :)**
